### PR TITLE
create: snap login -> sudo snap login

### PR DESCRIPTION
**Pull request by caldav**
## Done

Users need to run sudo snap login instead of snap login:

* Content fix in create/

## QA

"sudo snap login" works, "snap login" doesn't.

### CODE REVIEW

**Comment by nottrobin** [comment]
`snap login` works for me without sudo.

``` bash
$ whoami
robin
$ snap login robin.winslow@canonical.com
Password: 
Two-factor code: 308002
Login successful
```

Are you sure you need sudo?

**Comment by caldav** [comment]
What if you snap logout first?

**Comment by nottrobin** [comment]
Yep still works.

**Comment by nottrobin** [comment]
``` bash
dpkg -l | grep snapd
ii  snapd                                       2.0.3                                               amd64        Tool to interact with Ubuntu Core Snappy.
```

**Comment by caldav** [comment]
You don't seem to have `xenial-updates` enabled. You should be at least on 2.12. What's you snapcraft version?

**Comment by nottrobin** [comment]
2.12. I'll try to update.

**Comment by nottrobin** [comment]
Ah now it asks for `sudo`. Fair enough.

**Comment by nottrobin** [comment]
Fixes #190

**Pull request merged**
