### PR TITLE
Update Vanilla to 0.1.0

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done

- Updated Vanilla framework to the latest version `0.1.0`
- Added the `code-block` class name to use the Vanilla styling

## QA

- Run the site and check the pages look the same with the new Vanilla
- Check the code blocks have a border and have margin around them

## Issue / Card

Fixes: https://github.com/ubuntudesign/snapcraft.io/issues/154

### CODE REVIEW

**Comment by deadlight** [comment]
@anthonydillon : if I run the steps from the readme, I get an unstyled site. It looks like vanilla isn't building.

**Comment by anthonydillon** [comment]
I am not sure what to suggest. Is there any errors or npm logs? Maybe try
running `rm -rf node_modules && npm i && gulp`

**Comment by nottrobin** [comment]
Works for me, but the code blocks don't seem to have borders:

no border

**Comment by nottrobin** [comment]
Ah! After running `gulp sass`, they do :) :+1: merging

**Comment by nottrobin** [comment]
Ah! After running `gulp sass`, they do :) :+1: merging

**Pull request merged**
