### PR TITLE
adding openwrt logo and updating homepage layout to suit

### LINKED ISSUE #183: Add OpenWrt to the list of supported distributions
## Context

OpenWrt needs to be added to the homepage as a supported distro.

### Relevant links

* [OpenWrt logo](https://commons.wikimedia.org/wiki/File:Openwrt_Logo.svg) 
* [Change in /docs/install](https://github.com/CanonicalLtd/snappy-docs/blob/new-structure/core/install.md)
* https://openwrt.org/

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* added OpenWrt logo and updated homepage layout to fit

## QA

1. go to the homepage and see the OpenWrt logo

## Issue / Card

Fixes #183

## Screenshot

image

### CODE REVIEW

**Comment by barrymcgee** [comment]
Hmm.. this is what I'm seeing?

https://www.dropbox.com/s/u041s0420m1xs17/Screenshot%202016-08-23%2013.46.51.png?dl=0

**Comment by pmahnke** [comment]
@barrymcgee that looks like the css didn't build?

**Comment by barrymcgee** [comment]
@pmahnke You're right - the scss is failing with an error, I had to change `docs.scss` line 23 to:

```css
.documentation__content pre {
  @extend .code-block !optional;
  @extend .command-line !optional;

  border: 1px solid #cdcdcd;

  code {
    color: inherit;
  }
}
```

...in order to get the build to scss. This seems related to a previous change by @nottrobin?

**Comment by barrymcgee** [comment]
Aside from that, logo code and QA looks good.

**Comment by pmahnke** [comment]
I tested @barrymcgee's update and it looks good... merging

**Pull request merged**
