### PR TITLE
Remove npm from package deps

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

update npm to version 3.10.8

## QA

- Pull down code
- Run `npm i`
- Run `gulp`
- Ensure no errors

### CODE REVIEW

**Comment by nottrobin** [comment]
Is there any point having `npm` in `package.json`? What does it achieve?

**Comment by barrymcgee** [comment]
@nottrobin Good call - having removed it and tested the running of the site, I can't see anywhere it is used at all. Will change this PR to remove it.

**Comment by barrymcgee** [comment]
@nottrobin Ready for re-review...

**Comment by nottrobin** [comment]
@barrymcgee testing...

**Pull request merged**
