### PR TITLE
Update to align with copy docs

### PR DESCRIPTION
**Pull request by grahambancroft**
## Done

Bring the site in line with the copy docs. Some tidying

## QA

Check that the latest changes in the copy docs have been actioned

## Docs

Homepage doc: https://docs.google.com/document/d/1ON64UWyJV-lUuIDv7V1aG-4NvAaRoJ6lKSQhCXR48ho/edit
Create doc: https://docs.google.com/document/d/182l_u_9neVZS2ZOYHjdemi7wHju89-JqOgJCHcM-JQQ/edit

### CODE REVIEW

**Comment by anthonydillon** [comment]
There are no copy changes in this branch. Just `no-margin-bottom` classes added?

**Comment by grahambancroft** [comment]
@anthonydillon there is at line 129 of index.html

**Comment by grahambancroft** [comment]
@anthonydillon I’ve updated the copy doc so it matches the change at line 129

**Comment by anthonydillon** [comment]
Thanks :+1:

**Pull request merged**
