### PR TITLE
Add ./import-docs.sh

### PR DESCRIPTION
**Pull request by nottrobin**
A script for pulling in docs from canonicalltd/snappy-docs, and making them available at /docs.

QA
--

First make sure you have Python and Pip 3.5 or greater (`pip3 --version`). Then install `python-frontmatter`:

```
pip3 install python-frontmatter
```

Run docs script, before building the site:

```
./import-docs.sh
npm install
node_modules/gulp/bin/gulp.js
```

Visit http://127.0.0.1:3000/docs and check it looks okay.

### CODE REVIEW

**Comment by nottrobin** [comment]
@pmahnke why does this have the "in progress" label?

**Comment by nottrobin** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;XUbabHoA&#x2F;1403-write-import-script"> Write import script</a>

**Comment by caldav** [comment]
It seems that the docs importer breaks code comments starting with "#" in markdown code blocks. 

To reproduce, run the import command and compare docs/install/ with https://github.com/CanonicalLtd/snappy-docs/blob/new-structure/install/index.md

**Comment by nottrobin** [comment]
@caldav yes interesting. I spent a while looking into it. It seems we're running onto [this bug in Jekyll](https://github.com/jekyll/jekyll/issues/3724).

I believe this should already work on the latest version of Jekyll (`3.1.6`), but I've also [updated the Jekyll config](https://github.com/ubuntudesign/snapcraft.io/pull/47/commits/13f2192aab481029aae355fa9dd9d171c09df886) so hopefully this will now be fixed for all versions.

If it doesn't work for you, try upgrading Jekyll (`sudo gem update jekyll`).

**Comment by barrymcgee** [comment]
LGTM! :shipit:

**Pull request merged**
