### PR TITLE
Revert capitalisation

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

Nouns are not nouns, revert previous commits making Snaps and Snapcraft capitalised.

## QA
Run through code and check that nothing unexpected has been reverted.

## Issue / Card

Original request: #38 , Fixes: #98

### CODE REVIEW

**Comment by pmahnke** [comment]
LGTM +1, but you can merge

**Comment by ktatar156** [comment]
Hi,
when website snapcraft.io will be updated (Capital letters) ?

**Comment by barrymcgee** [comment]
@ktatar156 This change has already been deployed.

**Comment by ktatar156** [comment]
I think that not everywhere, examples:
"This way applications can be immutable for security reasons while still offering a full and rich user experience. To learn more about the makeup of a **snap** please see the snap architecture article."

"That means that **snaps** can’t peek around at your data - other than the data you give them"

and few more.

**Comment by barrymcgee** [comment]
@ktatar156 These should not be capitalised. Please not this change was to **revert** capitalisation, not introduce it.

**Comment by ktatar156** [comment]
Why not to use everywhere (except terminal commands) snap with big 'S'? Please look at example in my lang:

EN: You can install snap package everywhere!
PL: Możesz zainstalować paczkę snap wszędzie!

In my opinion, above looks ugly. And now:

EN: You can install Snap package everywhere!
PL: Możesz zainstalować paczkę Snap wszędzie!

Looks better and also help to tell do-not-translate that word (snap has few meanings in PL, like crack, break, photo, etc.), because it's product name.

**Comment by barrymcgee** [comment]
This is because 'snap' is written in lowercase as it is intended to be a natural noun, not a proper noun.

**Pull request merged**
