### PR TITLE
There aren't readme files to follow

### LINKED ISSUE #1: Build error…
Hey @anthonydillon I got all excited and tried to build this locally but it didn't work :-( I sat with Karl and Graham but we still couldn't work out why (and then Magda noticed I was taking up their time) ;-)

The error I get is this: 

```
(node:1292) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[10:18:30] Using gulpfile ~/Sites/snapcraft.io/Gulpfile.js
[10:18:30] Starting 'jekyll-build'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn jekyll ENOENT
    at exports._errnoException (util.js:953:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:449:3
```

Can you help?! 

P.s I had a wee look on Graham's mac, it's looking nice. (I thought you might be asked to do that this week) ;-)

### PR DESCRIPTION
**Pull request by markramm**
## Done

Reworking the language to remove reference to README files that don't exist.

### CODE REVIEW

**Comment by barrymcgee** [comment]
@markramm Does this address #157 completely?

**Comment by elopio** [comment]
I think this should be fixed in the tour source code instead. The idea of the READMES in each dir sounded good. The bug is here, waiting to see if @didrocks agrees: https://bugs.launchpad.net/snappy/+bug/1611094

**Comment by didrocks** [comment]
I'm unsure what strategy (in terms of updates, keeping content synced and so on) has @caldav on this, as he's now leading that effort. Deferring to him on that one. :)

**Comment by caldav** [comment]
I've added a new PR that fixes the rest of the page. Can be a temporary fix if READMEs appears in the tour, but I don't think having them in is a priority.

**Comment by elopio** [comment]
ack. Thank you!

**Pull request closed without merging**
